spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://TBD:3306/leadpet
    username: ${DB_USER:}
    password: ${DB_PASS:}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: false
      generate-ddl: true
      show-sql: true
  jpa:
    hibernate:
      ddl-auto: none